version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=Oracle_123
    ports:
      - "1521:1521"
    volumes:
      - ./oracle_data:/opt/oracle/oradata

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Postgres_123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data