version: '3'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=Cristian6093
    volumes:
      - oracle-data:/opt/oracle/oradata

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  oracle-data:
  postgres-data: